### PR TITLE
74 expo public text key crashes the app if null

### LINKED ISSUE #74: EXPO_PUBLIC_TEXT_KEY crashes the app if null
`EXPO_PUBLIC_TEXT_KEY` is used without checking for null.

### PR DESCRIPTION
**Pull request by Youssef-S-Negm**

### CODE REVIEW

File: components/screens/ChatScreen.js [hunk 1]
```diff
@@ -10,6 +10,22 @@ import ConfirmDeleteMessageButton from '../buttons/ConfirmDeleteMessageButton';
...
+        }
+    }
+
+    useEffect(() => {
+        handleDecryption()
+    }, [])
+
     if (sender.id === auth.currentUser.uid) {
         const date = new Date(item.sentAt)
         const formattedDate = date.getHours() + ':' + date.getMinutes()
```
Comment (Mgayar-sci) [inline components/screens/ChatScreen.js:31]: This if/else blocks seems very redundant! 
Try to do the redundant work above the if and only render the differed components inside the if/else.
